default:
  navigation:
    - title: Breakfast & Dairy
      subtitle: Categories
      url: /t/categories/breakfast-and-dairy
      items:
        - :title: Milk & Milk Products
          :url: /t/categories/breakfast-and-dairy/milk-and-milk-products
        - :title: Butter & Cheese
          :url: /t/categories/breakfast-and-dairy/butter-and-cheese
        - :title: Paneer & Curd
          :url: /t/categories/breakfast-and-dairy/paneer-and-curd
        - :title: Bread & Jams
          :url: /t/categories/breakfast-and-dairy/bread-and-jams
        - :title: Tea & Coffee
          :url: /t/categories/breakfast-and-dairy/tea-and-coffee
        - :title: Bakery Products
          :url: /t/categories/breakfast-and-dairy/bakery-products
        - :title: HealtKart
          :url: /t/categories/breakfast-and-dairy/healthkart
      promo_banners:
        - subtitle: New collection
          title: Summer 2019
          url: /t/new-collection/summer-2019
          image: 'meganav/promo_banner_left-first-category.jpg'
        - subtitle: Special Offers
          title: Get up to 30% off
          url: /t/special-offers/30-off
          image: 'meganav/promo_banner_right-first-category.jpg'
    - title: Icecream
      subtitle: Categories
      url: /t/categories/icecream
      items:
        - :title: Icecream packs
          :url: /t/categories/icecream/ice-cream-packs
        - :title: Novelties
          :url: /t/categories/icecream/novelties
        - :title: cakes
          :url: /t/categories/icecream/cakes
      promo_banners:
        - subtitle: New collection
          title: Summer 2019
          url: /t/new-collection/summer-2019
          image: 'meganav/promo_banner_left-second-category.jpg'
        - subtitle: Special Offers
          title: Get up to 30% off
          url: /t/special-offers/30-off
          image: 'meganav/promo_banner_right-second-category.jpg'
    - title: Packaged Foods
      subtitle: Categories
      url: /t/categories/packaged-foods
      items:
        - :title: Biscuits, Chocolates & Snacks
          :url: /t/categories/packaged-foods/biscuits-chocolates-and-snacks
        - :title: Noodles & Soups
          :url: /t/categories/packaged-foods/noodles-and-soups
        - :title: Sauces & Spreads
          :url: /t/categories/packaged-foods/sauces-and-spreads
        - :title: Baking & Dessert Items
          :url: /t/categories/packaged-foods/baking-and-dessert-items
        - :title: Dry Fruits & Nuts
          :url: /t/categories/packaged-foods/dry-fruits-and-nuts
        - :title: RTE & Frozen foods
          :url: /t/categories/packaged-foods/rte-and-frozen
        - :title: Baking & Dessert Items
          :url: /t/categories/packaged-foods/baking-and-dessert-items

      promo_banners:
        - subtitle: New collection
          title: Summer 2019
          url: /t/new-collection/summer-2019
          image: 'meganav/promo_banner_left-third-category.jpg'
        - subtitle: Special Offers
          title: Get up to 30% off
          url: /t/special-offers/30-off
          image: 'meganav/promo_banner_right-third-category.jpg'

    - title: Beverages
      subtitle: Categories
      url: /t/categories/beverages
      items:
        - :title: Cold Drinks
          :url: /t/categories/beverages/cold-drinks
        - :title: Tea & Coffee
          :url: /t/categories/beverages/tea-and-coffee
        - :title: Juices & Drinks
          :url: /t/categories/beverages/juices-and-drinks
        - :title: Health & Enery Drinks
          :url: /t/categories/beverages/health-and-energy-drinks
        - :title: Water & Soda
          :url: /t/categories/beverages/water-and-soda